---
title: "Violence against healthcare institutions and workers during wartime"
authors: Jon Meltzer, Eve Sampson
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Libraries

```{r}
library(tidyverse)
library(tigris)
library(janitor)
library(lubridate)
```

## Load Data test

```{r}
# ACLED
acled_afg <- read_csv("data/afghanistan_2001_2021.csv")
acled_ira <- read_csv("data/iraq_2002_present.csv")
acled_isr <- read_csv("data/israel-palestine_2001_present.csv")
acled_syr <- read_csv("data/syria_2010_present.csv")
acled_ukr <- read_csv("data/ukraine_2013_present.csv")
# WHO
who_afg <- read_csv("data/WHO_Afghanistan 2001.csv")
who_ira <- read_csv("data/WHO_Iraq_2002.csv")
who_syr <- read_csv("data/WHO_Syria_2010.csv")
who_ukr <- read_csv("data/WHO_Ukraine_2013.csv")
```

## Cleaning WHO

```{r}
who_afg <- clean_names(who_afg)
who_ira <- clean_names(who_ira)
who_syr <- clean_names(who_syr)
who_ukr <- clean_names(who_ukr)
```

## Basic analysis - violence against civilians by actors in Ukraine, daily

```{r}
ukr_civ <- acled_ukr %>% 
  filter(
    event_type == "Violence against civilians",
    fatalities > 0
  ) %>% 
  mutate(event_date=dmy(event_date)) %>% 
  group_by(event_date)

ukr_civ_naf <- acled_ukr %>% 
  filter(
    event_type == "Violence against civilians",
    fatalities > 0,
    actor1 == "NAF: United Armed Forces of Novorossiya"
  ) %>% 
  mutate(event_date=dmy(event_date)) %>% 
  group_by(event_date) %>% 
  summarize(
    count=n(),
    fatalities=sum(fatalities)
  )

ukr_civ_ru <- acled_ukr %>% 
  filter(
    event_type == "Violence against civilians",
    fatalities > 0,
    actor1 == "Military Forces of Russia (2000-)"
  ) %>% 
  mutate(event_date=dmy(event_date)) %>% 
  group_by(event_date) %>% 
  summarize(
    count=n(),
    fatalities=sum(fatalities)
  )

ukr_civ_uk <- acled_ukr %>% 
  filter(
    event_type == "Violence against civilians",
    fatalities > 0,
    actor1 == "Military Forces of Ukraine (2019-)" | actor1 == "Military Forces of Ukraine (2014-2019)"
  ) %>% 
  mutate(event_date=dmy(event_date)) %>% 
  group_by(event_date) %>% 
  summarize(count=n(),
    fatalities=sum(fatalities)
  )

ukr_civ_azov <- acled_ukr %>% 
  filter(
    event_type == "Violence against civilians",
    fatalities > 0,
    assoc_actor_1 == "Azov Battalion"
  ) %>% 
  mutate(event_date=dmy(event_date)) %>% 
  group_by(event_date) %>% 
  summarize(
    count=n(),
    fatalities=sum(fatalities)
  )

ukr_civ_anon <- acled_ukr %>% 
  filter(
    event_type == "Violence against civilians",
    fatalities > 0,
    actor1 == "Unidentified Armed Group (Ukraine)"
  ) %>% 
  mutate(event_date=dmy(event_date)) %>% 
  group_by(event_date) %>% 
  summarize(
    count=n(),
    fatalities=sum(fatalities)
  )

```

